name: Mirror dev to GitLab

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  mirror:
    # if: github.repository == 'accessibility-exchange/platform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "${{ vars.GIT_USER }}"
          git config --global user.email "${{ vars.GIT_EMAIL }}"
          git remote add gitlab ${{ vars.GITLAB_URL }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.GITLAB_SSH_KEY }}

#          ssh-keyscan git.kube.v1.colab.coop >> ~/.ssh/known_hosts
      - name: Push to GitLab
        run: |
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          git pull gitlab dev:development
          git push gitlab dev:development
